-- Renders comments to the Markdown an agent reads.
--
-- Pure: takes comments, returns a string. No IO, no store knowledge -- which keeps it
-- trivially testable and means a future non-local backend reuses it unchanged.
--
-- One direction only. Markdown is regenerated wholesale on every write and is never
-- parsed back, so `context` (needed for re-anchoring) never has to survive a round trip
-- through it.

local M = {}

local HEADER = [[
# Review comments

Generated by revu.nvim from `.revu/comments.json`. Edits here are overwritten on the next
write -- change comments in the editor instead.

Unchecked items are open; checked items are resolved.
]]

---@param a revu.Comment
---@param b revu.Comment
local function by_position(a, b)
  if a.path ~= b.path then
    return a.path < b.path
  end
  if a.line ~= b.line then
    return a.line < b.line
  end
  return (a.id or "") < (b.id or "")
end

---@param comments revu.Comment[]
---@return string
function M.render(comments)
  local sorted = vim.deepcopy(comments)
  table.sort(sorted, by_position)

  local out = { HEADER }
  local current_path

  for _, c in ipairs(sorted) do
    if c.path ~= current_path then
      current_path = c.path
      table.insert(out, ("\n## %s\n"):format(c.path))
    end

    local box = c.status == "resolved" and "x" or " "
    -- The old side is worth calling out; the new side is the default and stays implicit.
    local side = c.side == "old" and " _(old side)_" or ""
    local anchor = (c.anchor or ""):gsub("^%s+", "")
    local body = (c.body or ""):gsub("%s+$", "")

    if anchor ~= "" then
      table.insert(out, ("- [%s] **L%d**%s `%s` — %s"):format(box, c.line, side, anchor, body))
    else
      table.insert(out, ("- [%s] **L%d**%s — %s"):format(box, c.line, side, body))
    end
  end

  if #out == 1 then
    table.insert(out, "\n_No comments._")
  end

  return table.concat(out, "\n") .. "\n"
end

return M
